version: '3.8'

services:
  multimodal-rag:
    build: .
    container_name: multimodal-rag-system
    ports:
      - "8000:8000"
    volumes:
      # Mount data directories for persistence
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
      # Mount models directory for local models
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - rag-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      # Persist ollama models
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - rag-network
    restart: unless-stopped
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Optional: ChromaDB as alternative vector store
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma-server
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - rag-network
    restart: unless-stopped

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  ollama-data:
    driver: local
  chroma-data:
    driver: local
  redis-data:
    driver: local

networks:
  rag-network:
    driver: bridge
